### PR TITLE
Add more rubies to travis

### PR DESCRIPTION
**Pull request by tomelm**
More Travis coverage

### CODE REVIEW

**Comment by tomelm** [comment]
@mittonk This look fine? Adding more Ruby versions to Travis and disabled sudo

**Comment by watterso** [comment]
You get my :shipit: !
Just to be clear adding those rvm versions means it will run the all the tests with those versions of ruby, correct?

**Comment by tomelm** [comment]
Yep! You can see the Travis build for the PR to verify: https://travis-ci.org/Yelp/yelp-ruby/builds/88223680

**Comment by watterso** [comment]
Nice, thanks!

**Comment by mittonk** [comment]
:shipit:

**Pull request merged**
