### PR TITLE
Compatibility bump

### PR DESCRIPTION
**Pull request by zshannon**
I ran into some compatibility issues with the gemspec version requirement for `simple_oauth`, so I bumped it. All tests pass, so I think it should be OK to merge.

### CODE REVIEW

**Comment by tomelm** [comment]
What branch did you fork off of? Those commits shouldn't be there...

**Comment by zshannon** [comment]
Weird. I forked off `develop` and `git log` looks nothing like this. I think it's a Github bug.

**Comment by tomelm** [comment]
No worries, sorry about the slowness on my part. Give me a day or so to double check that we won't have any weirdness with merging and I'll pull this in.

Thanks again for helping out! :D

**Comment by tomelm** [comment]
@zshannon really sorry, this completely fell off my radar. I'm going to close this in favor of #31 as it uses a newer version.

**Pull request closed without merging**
