### PR TITLE
Business endpoint should handle Unicode business IDs.  Refs #51.

### PR DESCRIPTION
**Pull request by mittonk**

### CODE REVIEW

**Comment by mittonk** [comment]
@tomelm : Not sure a cassette-based test would be helpful here, but might.
A proper unittest would be nice, but I have a lot to learn.

Interactive testing works, minimal repro case from issue now gives:
```
Momofuku Má Pêche
```
(after hacking around SSL issues in #56).

Does this deserve a version bump?

**Comment by tomelm** [comment]
A cassette based test would be nice to ensure we don't introduce regressions later on.

As far as version bump, yea we should have one for this. We'll handle that later on when we release.

**Comment by mittonk** [comment]
@tomelm : I don't think I'll manage a VCR-based test anytime soon.

I think our choices are "fix without test" or "leave broken".

I'd prefer "fix without test", how about a ship-it?

**Comment by ajm188** [comment]
@mittonk I'm also okay with "fix without test", as long as we open an issue for getting a VCR test on this.

**Comment by mittonk** [comment]
Filed #64 to add tests in a later pass.

**Comment by tomelm** [comment]
:shipit:

**Pull request merged**
