### PR TITLE
Specify the invalid parameter received when creating an invalid param…

### PR DESCRIPTION
**Pull request by ldrbrandon**
…eter error

### CODE REVIEW

**Comment by tomelm** [comment]
@ldrbrandon I'll look at this more but you'll need to update the so we have a clean CI run before we can consider this

**Comment by ldrbrandon** [comment]
Sorry you said update so ... What are you referring to?

**Comment by tomelm** [comment]
(whoops, missed a word)

You need to update the tests. our CI is failing: https://travis-ci.org/Yelp/yelp-ruby/builds/70281379

**Comment by ldrbrandon** [comment]
Ah yes. Thanks, working on it!

**Comment by ldrbrandon** [comment]
I made some tweaks and got the tests passing. The only one I was having
issues with was 'raise internal error' in error_spec.rb

My apologies if I make rookie mistakes here. I removed the specific error
message expectancy, not sure if that is good/bad, but it helped the test
pass and it's still throwing the right error.

Brandon

**Comment by tomelm** [comment]
Alright! I'll check this out this week. Thanks for fixing that!

**Comment by ldrbrandon** [comment]
Great! Let me know if there's anything I could do to make it better in any
way!

Brandon

**Comment by ldrbrandon** [comment]
Can this one get merged yet or are there outstanding issues?

**Comment by tomelm** [comment]
@ldrbrandon yep, sorry! Never noticed the tests were fixed and this fell off my radar.

**Comment by tomelm** [comment]
@ldrbrandon I'll cut a new version of the gem in the next few days and will let you know when it's deployed

**Comment by ldrbrandon** [comment]
@tomelm No worries. Thanks!

**Comment by tomelm** [comment]
@ldrbrandon released! https://rubygems.org/gems/yelp

**Pull request merged**
